FINANCIAL_EXTRACTION_PROMPT = """
Eres un extractor financiero experto. Tu objetivo es extraer métricas comparativas útiles de documentos económicos, financieros, empresariales o reportes tipo 10-Q / 10-K.

REGLAS DE PRIORIDAD:
Busca primero estas métricas si están presentes:

1. INCOME STATEMENT / STATEMENT OF OPERATIONS:
- Total net sales
- Net sales
- Revenue
- Gross margin
- Operating income
- Income before provision for income taxes
- Net income
- Research and development
- Selling, general and administrative
- Total operating expenses

2. PRODUCT / SERVICE CATEGORIES:
- Products
- Services
- iPhone
- Mac
- iPad
- Wearables, Home and Accessories

3. REPORTABLE SEGMENTS:
- Americas
- Europe
- Greater China
- Japan
- Rest of Asia Pacific

4. BALANCE SHEET:
- Cash and cash equivalents
- Marketable securities
- Total current assets
- Total non-current assets
- Total assets
- Accounts payable
- Total current liabilities
- Total non-current liabilities
- Total liabilities
- Total shareholders' equity
- Total liabilities and shareholders' equity

5. CASH FLOW:
- Cash generated by operating activities
- Cash generated by/(used in) investing activities
- Cash used in financing activities
- Increase in cash, cash equivalents, and restricted cash and cash equivalents
- Cash, cash equivalents, and restricted cash and cash equivalents, ending balances

INSTRUCCIONES OBLIGATORIAS:
- Extrae solo filas que tengan DOS valores numéricos comparables.
- value_1 debe ser el valor del periodo más reciente o actual.
- value_2 debe ser el valor del periodo anterior o comparativo.
- No inventes cifras.
- No calcules porcentajes ni variaciones.
- No incluyas filas sin dos valores comparables claros.
- No incluyas texto legal, firmas, certificaciones, metadatos SEC, cabeceras o notas irrelevantes.
- Limpia símbolos de moneda.
- Convierte números con comas a valores numéricos.
- Interpreta paréntesis como valores negativos.
- Mantén el label financiero claro y breve.
- Si puedes identificar statement, usa uno de estos valores:
  - income_statement
  - balance_sheet
  - cash_flow
  - revenue_by_category
  - revenue_by_segment
  - other
- Si puedes identificar section, usa una etiqueta breve como:
  - net_sales
  - gross_margin
  - operating_expenses
  - assets
  - liabilities
  - equity
  - operating_activities
  - investing_activities
  - financing_activities
  - products_services
  - segments

Texto del documento:
{texto}
"""

ANALYTICS_INSIGHTS_PROMPT = """
Analiza las siguientes métricas financieras estructuradas y genera insights de negocio.

Reglas obligatorias:
- No inventes valores.
- Usa solo los datos proporcionados.
- No añadas cifras que no aparezcan en los datos.
- Prioriza variaciones relevantes, crecimiento, caídas y métricas clave.
- Si no hay datos suficientes, dilo claramente.
- Devuelve entre 3 y 6 insights.
- Cada insight debe ser una frase clara y breve.

Datos estructurados:
{datos}
"""

CHART_SUGGESTION_PROMPT = """
A partir de los datos estructurados proporcionados, sugiere gráficas útiles.

Reglas:
- No inventes datos.
- Usa solo los datos proporcionados.
- Sugiere solo gráficas con sentido.
- Usa bar chart para comparativas por categoría.
- Usa line chart para series temporales.
- Evita pie chart si hay demasiadas categorías.

Datos:
{datos}
"""