import os
from dotenv import load_dotenv

load_dotenv()


OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

DEFAULT_MODEL_NAME = "gpt-5-mini"
DEFAULT_MODEL_TEMPERATURE = 0.2

MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024
MAX_TEXT_LENGTH_CHARS = 1_500_000
MAX_FRAGMENTS = 80
MAX_TARGET_WORDS = 5000

MIN_SUMMARY_PERCENTAGE = 10
MAX_SUMMARY_PERCENTAGE = 80

DEFAULT_MODEL_NAME = "gpt-5-mini"
DEFAULT_MODEL_TEMPERATURE = 0.2

CHUNK_SIZE = 8000
CHUNK_OVERLAP = 500
LARGE_DOCUMENT_BATCH_SIZE = 4
MAX_SUMMARY_WORKERS = 4